# my global config
global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'kafka_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['kafka_exporter:9308']
        labels:
          group: 'kafka_exporter'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090', 'cadvisor:8085', 'node-exporter:9100']
